{% set version = "1.0.7" %}


package:
  name: xcube_geodb
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-geodb/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5eb6f7ac9a277d669a60bd7ccd489d226422cbd52085088ef4f554e9baf3b676

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - geopandas
    - python-keycloak    
    - matplotlib-base
    - psycopg2
    - requests
    - ipyleaflet
    - python-fastjsonschema
    - python-dotenv

test:
  imports:
    - xcube_geodb.core.geodb

about:
  summary: xcube geoDB is a geo-spatial database within the xcube ecosystem.
  home: https://github.com/xcube-dev/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: geodb is a Python package
  doc_url: https://xcube_geodb.readthedocs.io
  dev_url: https://github.com/xcube-dev/xcube-geodb

extra:
  recipe-maintainers:
    - pont-us
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
    - TejasMorbagal
