{% set version = "1.0.5" %}


package:
  name: xcube_geodb
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-geodb/archive/v{{ version }}.tar.gz
  sha256: e0e672edb2a15edaaa6b65641a48704bf4beba4888d36cab964bae690a3dfc52

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - geopandas
    - psycopg2
    - requests
    - ipyleaflet

test:
  imports:
    - xcube_geodb.core.geodb

about:
  summary: geodb is a Python package
  home: https://github.com/dcs4cop/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: geodb is a Python package
  doc_url: https://xcube_geodb.readthedocs.io
  dev_url: https://github.com/dcs4cop/xcube-geodb

extra:
  recipe-maintainers:
    - pont-us
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
