{% set version = "1.0.6" %}


package:
  name: xcube_geodb
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-geodb/archive/v{{ version }}.tar.gz
  sha256: f99bfb2b94b7856b41e56edcc29aadee635239b0b6f2cc596797fcc9f0a3a316

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - geopandas
    - matplotlib-base
    - psycopg2
    - postgis
    - requests
    - ipyleaflet
    - python-fastjsonschema
    - python-dotenv

test:
  imports:
    - xcube_geodb.core.geodb

about:
  summary: geodb is a Python package
  home: https://github.com/dcs4cop/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: geodb is a Python package
  doc_url: https://xcube_geodb.readthedocs.io
  dev_url: https://github.com/dcs4cop/xcube-geodb

extra:
  recipe-maintainers:
    - pont-us
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
    - TejasMorbagal
