{% set version = "1.0.3" %}


package:
  name: xcube_geodb
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-geodb/archive/v{{ version }}.tar.gz
  sha256: C13C7103C63495D8D9A29C6A65E617C08073F6383021FB53DAC3A945E8C28329

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - geopandas
    - matplotlib-base
    - descartes
    - psycopg2
    - requests
    - ipyleaflet
    - python-fastjsonschema
    - python-dotenv

test:
  imports:
    - xcube_geodb.core.geodb

about:
  summary: geodb is a Python package
  home: https://github.com/dcs4cop/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: geodb is a Python package
  doc_url: https://xcube_geodb.readthedocs.io
  dev_url: https://github.com/dcs4cop/xcube-geodb

extra:
  recipe-maintainers:
    - pont-us
    - dzelge
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
