{% set version = "0.1.16" %}


package:
  name: xcube_geodb
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-geodb/archive/v{{ version }}.tar.gz
  sha256: c8366d94566a212740aa39a744d37a7de743f107e5fae9e4ae4bcef06d72d7c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - geopandas >=0.5
    - matplotlib-base
    - descartes
    - requests
    - python-dotenv
    - shapely
    - pandas
    - click

test:
  imports:
    - xcube_geodb.core.geodb

about:
  summary: geodb is a Python package
  home: https://github.com/dcs4cop/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: geodb is a Python package
  doc_url: https://xcube_geodb.readthedocs.io
  dev_url: https://github.com/dcs4cop/xcube-geodb

extra:
  recipe-maintainers:
    - pont-us
    - dzelge
    - TonioF
    - forman
    - AliceBalfanz
