{% set version = "0.1.4" %}

package:
  name: xcube_geodb
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-geodb/archive/v{{ version }}.tar.gz
  sha256: d689992738ad70f26e0e10f614ca048ce22c63eab7d827d32d85a1561fb86e4a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - xcube >=0.3.0
    - geopandas >=0.5
    - matplotlib-base
    - descartes
    - requests
    - sphinx
    - python-dotenv
    - jupyterlab

test:
  imports:
    - xcube_geodb.core.geodb

about:
  summary: "geodb is a Python package"
  home: https://github.com/dcs4cop/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: "geodb is a Python package"
  doc_url: https://xcube_geodb.readthedocs.io
  dev_url: https://github.com/dcs4cop/xcube-geodb

extra:
  recipe-maintainers:
    - dzelge
    - forman
